# Generated by Django 4.1.6 on 2023-03-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticidelist',
            name='ddesc',
            field=models.CharField(max_length=500),
        ),
    ]
